admin, addresses, create
admin, addresses, delete
admin, addresses, read
admin, addresses, update
admin, carts, create
admin, carts, delete
admin, carts, read
admin, carts, update
admin, orders, create
admin, orders, delete
admin, orders, read
admin, orders, update
admin, payments, create
admin, payments, read
role_0, orders, delete
role_0, promos, delete
role_2, orders, delete
role_2, promos, delete
role_4, orders, delete
role_4, promos, delete
role_6, orders, delete
role_6, promos, delete
role_8, orders, delete
role_8, promos, delete
staff, addresses, create
staff, addresses, delete
staff, addresses, read
staff, carts, read
staff, orders, read
staff, orders, update
staff, payments, create
staff, payments, read
tenant, addresses, create
tenant, addresses, delete
tenant, addresses, read
tenant, addresses, update
tenant, carts, create
tenant, carts, delete
tenant, carts, read
tenant, carts, update
tenant, orders, create
tenant, orders, read
tenant, payments, create
tenant, payments, read
