// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/dynamic-pricing.proto

package dynamicpricingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFlashSaleByProductIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlashSaleByProductIdRequest) Reset() {
	*x = GetFlashSaleByProductIdRequest{}
	mi := &file_proto_dynamic_pricing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlashSaleByProductIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlashSaleByProductIdRequest) ProtoMessage() {}

func (x *GetFlashSaleByProductIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamic_pricing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlashSaleByProductIdRequest.ProtoReflect.Descriptor instead.
func (*GetFlashSaleByProductIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_dynamic_pricing_proto_rawDescGZIP(), []int{0}
}

func (x *GetFlashSaleByProductIdRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type GetFlashSaleByVariantIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VariantId     string                 `protobuf:"bytes,2,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlashSaleByVariantIdRequest) Reset() {
	*x = GetFlashSaleByVariantIdRequest{}
	mi := &file_proto_dynamic_pricing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlashSaleByVariantIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlashSaleByVariantIdRequest) ProtoMessage() {}

func (x *GetFlashSaleByVariantIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamic_pricing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlashSaleByVariantIdRequest.ProtoReflect.Descriptor instead.
func (*GetFlashSaleByVariantIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_dynamic_pricing_proto_rawDescGZIP(), []int{1}
}

func (x *GetFlashSaleByVariantIdRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetFlashSaleByVariantIdRequest) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

type GetPromoByCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPromoByCodeRequest) Reset() {
	*x = GetPromoByCodeRequest{}
	mi := &file_proto_dynamic_pricing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPromoByCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromoByCodeRequest) ProtoMessage() {}

func (x *GetPromoByCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamic_pricing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromoByCodeRequest.ProtoReflect.Descriptor instead.
func (*GetPromoByCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_dynamic_pricing_proto_rawDescGZIP(), []int{2}
}

func (x *GetPromoByCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ApplyPromoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyPromoRequest) Reset() {
	*x = ApplyPromoRequest{}
	mi := &file_proto_dynamic_pricing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPromoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPromoRequest) ProtoMessage() {}

func (x *ApplyPromoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamic_pricing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPromoRequest.ProtoReflect.Descriptor instead.
func (*ApplyPromoRequest) Descriptor() ([]byte, []int) {
	return file_proto_dynamic_pricing_proto_rawDescGZIP(), []int{3}
}

func (x *ApplyPromoRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ApplyPromoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ApplyPromoRequest) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type ApplyPromoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Discount      int64                  `protobuf:"varint,1,opt,name=discount,proto3" json:"discount,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyPromoResponse) Reset() {
	*x = ApplyPromoResponse{}
	mi := &file_proto_dynamic_pricing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPromoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPromoResponse) ProtoMessage() {}

func (x *ApplyPromoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamic_pricing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPromoResponse.ProtoReflect.Descriptor instead.
func (*ApplyPromoResponse) Descriptor() ([]byte, []int) {
	return file_proto_dynamic_pricing_proto_rawDescGZIP(), []int{4}
}

func (x *ApplyPromoResponse) GetDiscount() int64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *ApplyPromoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApplyPromoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FlashSale struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProductId       string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VariantId       string                 `protobuf:"bytes,4,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	DiscountPercent int32                  `protobuf:"varint,5,opt,name=discount_percent,json=discountPercent,proto3" json:"discount_percent,omitempty"`
	Stock           int64                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	MaxPerUser      int32                  `protobuf:"varint,7,opt,name=max_per_user,json=maxPerUser,proto3" json:"max_per_user,omitempty"`
	StartTime       string                 `protobuf:"bytes,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime         string                 `protobuf:"bytes,9,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IsActive        bool                   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FlashSale) Reset() {
	*x = FlashSale{}
	mi := &file_proto_dynamic_pricing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlashSale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashSale) ProtoMessage() {}

func (x *FlashSale) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamic_pricing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashSale.ProtoReflect.Descriptor instead.
func (*FlashSale) Descriptor() ([]byte, []int) {
	return file_proto_dynamic_pricing_proto_rawDescGZIP(), []int{5}
}

func (x *FlashSale) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FlashSale) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FlashSale) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *FlashSale) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *FlashSale) GetDiscountPercent() int32 {
	if x != nil {
		return x.DiscountPercent
	}
	return 0
}

func (x *FlashSale) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *FlashSale) GetMaxPerUser() int32 {
	if x != nil {
		return x.MaxPerUser
	}
	return 0
}

func (x *FlashSale) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *FlashSale) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *FlashSale) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type Promo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code                string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Description         string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	DiscountType        string                 `protobuf:"bytes,5,opt,name=discount_type,json=discountType,proto3" json:"discount_type,omitempty"`
	DiscountValue       int64                  `protobuf:"varint,6,opt,name=discount_value,json=discountValue,proto3" json:"discount_value,omitempty"`
	MinPurchase         int64                  `protobuf:"varint,7,opt,name=min_purchase,json=minPurchase,proto3" json:"min_purchase,omitempty"`
	MaxDiscount         int64                  `protobuf:"varint,8,opt,name=max_discount,json=maxDiscount,proto3" json:"max_discount,omitempty"`
	Quantity            int32                  `protobuf:"varint,9,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UsedCount           int32                  `protobuf:"varint,10,opt,name=used_count,json=usedCount,proto3" json:"used_count,omitempty"`
	MaxUsagePerUser     int32                  `protobuf:"varint,11,opt,name=max_usage_per_user,json=maxUsagePerUser,proto3" json:"max_usage_per_user,omitempty"`
	CanCombineFlashSale bool                   `protobuf:"varint,12,opt,name=can_combine_flash_sale,json=canCombineFlashSale,proto3" json:"can_combine_flash_sale,omitempty"`
	StartDate           string                 `protobuf:"bytes,13,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate             string                 `protobuf:"bytes,14,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	IsActive            bool                   `protobuf:"varint,15,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Promo) Reset() {
	*x = Promo{}
	mi := &file_proto_dynamic_pricing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Promo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Promo) ProtoMessage() {}

func (x *Promo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamic_pricing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Promo.ProtoReflect.Descriptor instead.
func (*Promo) Descriptor() ([]byte, []int) {
	return file_proto_dynamic_pricing_proto_rawDescGZIP(), []int{6}
}

func (x *Promo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Promo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Promo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Promo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Promo) GetDiscountType() string {
	if x != nil {
		return x.DiscountType
	}
	return ""
}

func (x *Promo) GetDiscountValue() int64 {
	if x != nil {
		return x.DiscountValue
	}
	return 0
}

func (x *Promo) GetMinPurchase() int64 {
	if x != nil {
		return x.MinPurchase
	}
	return 0
}

func (x *Promo) GetMaxDiscount() int64 {
	if x != nil {
		return x.MaxDiscount
	}
	return 0
}

func (x *Promo) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Promo) GetUsedCount() int32 {
	if x != nil {
		return x.UsedCount
	}
	return 0
}

func (x *Promo) GetMaxUsagePerUser() int32 {
	if x != nil {
		return x.MaxUsagePerUser
	}
	return 0
}

func (x *Promo) GetCanCombineFlashSale() bool {
	if x != nil {
		return x.CanCombineFlashSale
	}
	return false
}

func (x *Promo) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Promo) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *Promo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

var File_proto_dynamic_pricing_proto protoreflect.FileDescriptor

const file_proto_dynamic_pricing_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/dynamic-pricing.proto\x12\x0fdynamic_pricing\"?\n" +
	"\x1eGetFlashSaleByProductIdRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"^\n" +
	"\x1eGetFlashSaleByVariantIdRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x02 \x01(\tR\tvariantId\"+\n" +
	"\x15GetPromoByCodeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"c\n" +
	"\x11ApplyPromoRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x03R\vtotalAmount\"d\n" +
	"\x12ApplyPromoResponse\x12\x1a\n" +
	"\bdiscount\x18\x01 \x01(\x03R\bdiscount\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xa7\x02\n" +
	"\tFlashSale\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x04 \x01(\tR\tvariantId\x12)\n" +
	"\x10discount_percent\x18\x05 \x01(\x05R\x0fdiscountPercent\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x03R\x05stock\x12 \n" +
	"\fmax_per_user\x18\a \x01(\x05R\n" +
	"maxPerUser\x12\x1d\n" +
	"\n" +
	"start_time\x18\b \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\t \x01(\tR\aendTime\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\"\xe7\x03\n" +
	"\x05Promo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\rdiscount_type\x18\x05 \x01(\tR\fdiscountType\x12%\n" +
	"\x0ediscount_value\x18\x06 \x01(\x03R\rdiscountValue\x12!\n" +
	"\fmin_purchase\x18\a \x01(\x03R\vminPurchase\x12!\n" +
	"\fmax_discount\x18\b \x01(\x03R\vmaxDiscount\x12\x1a\n" +
	"\bquantity\x18\t \x01(\x05R\bquantity\x12\x1d\n" +
	"\n" +
	"used_count\x18\n" +
	" \x01(\x05R\tusedCount\x12+\n" +
	"\x12max_usage_per_user\x18\v \x01(\x05R\x0fmaxUsagePerUser\x123\n" +
	"\x16can_combine_flash_sale\x18\f \x01(\bR\x13canCombineFlashSale\x12\x1d\n" +
	"\n" +
	"start_date\x18\r \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x0e \x01(\tR\aendDate\x12\x1b\n" +
	"\tis_active\x18\x0f \x01(\bR\bisActive2\x90\x03\n" +
	"\x15DynamicPricingService\x12f\n" +
	"\x17GetFlashSaleByProductId\x12/.dynamic_pricing.GetFlashSaleByProductIdRequest\x1a\x1a.dynamic_pricing.FlashSale\x12f\n" +
	"\x17GetFlashSaleByVariantId\x12/.dynamic_pricing.GetFlashSaleByVariantIdRequest\x1a\x1a.dynamic_pricing.FlashSale\x12P\n" +
	"\x0eGetPromoByCode\x12&.dynamic_pricing.GetPromoByCodeRequest\x1a\x16.dynamic_pricing.Promo\x12U\n" +
	"\n" +
	"ApplyPromo\x12\".dynamic_pricing.ApplyPromoRequest\x1a#.dynamic_pricing.ApplyPromoResponseBHZFkaffein/dynamic-pricing-service/proto/dynamic-pricing;dynamicpricingpbb\x06proto3"

var (
	file_proto_dynamic_pricing_proto_rawDescOnce sync.Once
	file_proto_dynamic_pricing_proto_rawDescData []byte
)

func file_proto_dynamic_pricing_proto_rawDescGZIP() []byte {
	file_proto_dynamic_pricing_proto_rawDescOnce.Do(func() {
		file_proto_dynamic_pricing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dynamic_pricing_proto_rawDesc), len(file_proto_dynamic_pricing_proto_rawDesc)))
	})
	return file_proto_dynamic_pricing_proto_rawDescData
}

var file_proto_dynamic_pricing_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_dynamic_pricing_proto_goTypes = []any{
	(*GetFlashSaleByProductIdRequest)(nil), // 0: dynamic_pricing.GetFlashSaleByProductIdRequest
	(*GetFlashSaleByVariantIdRequest)(nil), // 1: dynamic_pricing.GetFlashSaleByVariantIdRequest
	(*GetPromoByCodeRequest)(nil),          // 2: dynamic_pricing.GetPromoByCodeRequest
	(*ApplyPromoRequest)(nil),              // 3: dynamic_pricing.ApplyPromoRequest
	(*ApplyPromoResponse)(nil),             // 4: dynamic_pricing.ApplyPromoResponse
	(*FlashSale)(nil),                      // 5: dynamic_pricing.FlashSale
	(*Promo)(nil),                          // 6: dynamic_pricing.Promo
}
var file_proto_dynamic_pricing_proto_depIdxs = []int32{
	0, // 0: dynamic_pricing.DynamicPricingService.GetFlashSaleByProductId:input_type -> dynamic_pricing.GetFlashSaleByProductIdRequest
	1, // 1: dynamic_pricing.DynamicPricingService.GetFlashSaleByVariantId:input_type -> dynamic_pricing.GetFlashSaleByVariantIdRequest
	2, // 2: dynamic_pricing.DynamicPricingService.GetPromoByCode:input_type -> dynamic_pricing.GetPromoByCodeRequest
	3, // 3: dynamic_pricing.DynamicPricingService.ApplyPromo:input_type -> dynamic_pricing.ApplyPromoRequest
	5, // 4: dynamic_pricing.DynamicPricingService.GetFlashSaleByProductId:output_type -> dynamic_pricing.FlashSale
	5, // 5: dynamic_pricing.DynamicPricingService.GetFlashSaleByVariantId:output_type -> dynamic_pricing.FlashSale
	6, // 6: dynamic_pricing.DynamicPricingService.GetPromoByCode:output_type -> dynamic_pricing.Promo
	4, // 7: dynamic_pricing.DynamicPricingService.ApplyPromo:output_type -> dynamic_pricing.ApplyPromoResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_dynamic_pricing_proto_init() }
func file_proto_dynamic_pricing_proto_init() {
	if File_proto_dynamic_pricing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dynamic_pricing_proto_rawDesc), len(file_proto_dynamic_pricing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dynamic_pricing_proto_goTypes,
		DependencyIndexes: file_proto_dynamic_pricing_proto_depIdxs,
		MessageInfos:      file_proto_dynamic_pricing_proto_msgTypes,
	}.Build()
	File_proto_dynamic_pricing_proto = out.File
	file_proto_dynamic_pricing_proto_goTypes = nil
	file_proto_dynamic_pricing_proto_depIdxs = nil
}
