// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/dynamic-pricing.proto

package dynamicpricingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DynamicPricingService_GetFlashSaleByProductId_FullMethodName = "/dynamic_pricing.DynamicPricingService/GetFlashSaleByProductId"
	DynamicPricingService_GetFlashSaleByVariantId_FullMethodName = "/dynamic_pricing.DynamicPricingService/GetFlashSaleByVariantId"
	DynamicPricingService_GetPromoByCode_FullMethodName          = "/dynamic_pricing.DynamicPricingService/GetPromoByCode"
	DynamicPricingService_ApplyPromo_FullMethodName              = "/dynamic_pricing.DynamicPricingService/ApplyPromo"
	DynamicPricingService_DecrementFlashSaleStock_FullMethodName = "/dynamic_pricing.DynamicPricingService/DecrementFlashSaleStock"
	DynamicPricingService_IncrementFlashSaleUsage_FullMethodName = "/dynamic_pricing.DynamicPricingService/IncrementFlashSaleUsage"
	DynamicPricingService_GetPromoUsage_FullMethodName           = "/dynamic_pricing.DynamicPricingService/GetPromoUsage"
)

// DynamicPricingServiceClient is the client API for DynamicPricingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DynamicPricingServiceClient interface {
	GetFlashSaleByProductId(ctx context.Context, in *GetFlashSaleByProductIdRequest, opts ...grpc.CallOption) (*FlashSale, error)
	GetFlashSaleByVariantId(ctx context.Context, in *GetFlashSaleByVariantIdRequest, opts ...grpc.CallOption) (*FlashSale, error)
	GetPromoByCode(ctx context.Context, in *GetPromoByCodeRequest, opts ...grpc.CallOption) (*Promo, error)
	ApplyPromo(ctx context.Context, in *ApplyPromoRequest, opts ...grpc.CallOption) (*ApplyPromoResponse, error)
	DecrementFlashSaleStock(ctx context.Context, in *DecrementFlashSaleStockRequest, opts ...grpc.CallOption) (*DecrementFlashSaleStockResponse, error)
	IncrementFlashSaleUsage(ctx context.Context, in *IncrementFlashSaleUsageRequest, opts ...grpc.CallOption) (*IncrementFlashSaleUsageResponse, error)
	GetPromoUsage(ctx context.Context, in *GetPromoUsageRequest, opts ...grpc.CallOption) (*PromoUsageResponse, error)
}

type dynamicPricingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDynamicPricingServiceClient(cc grpc.ClientConnInterface) DynamicPricingServiceClient {
	return &dynamicPricingServiceClient{cc}
}

func (c *dynamicPricingServiceClient) GetFlashSaleByProductId(ctx context.Context, in *GetFlashSaleByProductIdRequest, opts ...grpc.CallOption) (*FlashSale, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlashSale)
	err := c.cc.Invoke(ctx, DynamicPricingService_GetFlashSaleByProductId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicPricingServiceClient) GetFlashSaleByVariantId(ctx context.Context, in *GetFlashSaleByVariantIdRequest, opts ...grpc.CallOption) (*FlashSale, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlashSale)
	err := c.cc.Invoke(ctx, DynamicPricingService_GetFlashSaleByVariantId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicPricingServiceClient) GetPromoByCode(ctx context.Context, in *GetPromoByCodeRequest, opts ...grpc.CallOption) (*Promo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Promo)
	err := c.cc.Invoke(ctx, DynamicPricingService_GetPromoByCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicPricingServiceClient) ApplyPromo(ctx context.Context, in *ApplyPromoRequest, opts ...grpc.CallOption) (*ApplyPromoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyPromoResponse)
	err := c.cc.Invoke(ctx, DynamicPricingService_ApplyPromo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicPricingServiceClient) DecrementFlashSaleStock(ctx context.Context, in *DecrementFlashSaleStockRequest, opts ...grpc.CallOption) (*DecrementFlashSaleStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecrementFlashSaleStockResponse)
	err := c.cc.Invoke(ctx, DynamicPricingService_DecrementFlashSaleStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicPricingServiceClient) IncrementFlashSaleUsage(ctx context.Context, in *IncrementFlashSaleUsageRequest, opts ...grpc.CallOption) (*IncrementFlashSaleUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncrementFlashSaleUsageResponse)
	err := c.cc.Invoke(ctx, DynamicPricingService_IncrementFlashSaleUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicPricingServiceClient) GetPromoUsage(ctx context.Context, in *GetPromoUsageRequest, opts ...grpc.CallOption) (*PromoUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromoUsageResponse)
	err := c.cc.Invoke(ctx, DynamicPricingService_GetPromoUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DynamicPricingServiceServer is the server API for DynamicPricingService service.
// All implementations must embed UnimplementedDynamicPricingServiceServer
// for forward compatibility.
type DynamicPricingServiceServer interface {
	GetFlashSaleByProductId(context.Context, *GetFlashSaleByProductIdRequest) (*FlashSale, error)
	GetFlashSaleByVariantId(context.Context, *GetFlashSaleByVariantIdRequest) (*FlashSale, error)
	GetPromoByCode(context.Context, *GetPromoByCodeRequest) (*Promo, error)
	ApplyPromo(context.Context, *ApplyPromoRequest) (*ApplyPromoResponse, error)
	DecrementFlashSaleStock(context.Context, *DecrementFlashSaleStockRequest) (*DecrementFlashSaleStockResponse, error)
	IncrementFlashSaleUsage(context.Context, *IncrementFlashSaleUsageRequest) (*IncrementFlashSaleUsageResponse, error)
	GetPromoUsage(context.Context, *GetPromoUsageRequest) (*PromoUsageResponse, error)
	mustEmbedUnimplementedDynamicPricingServiceServer()
}

// UnimplementedDynamicPricingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDynamicPricingServiceServer struct{}

func (UnimplementedDynamicPricingServiceServer) GetFlashSaleByProductId(context.Context, *GetFlashSaleByProductIdRequest) (*FlashSale, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFlashSaleByProductId not implemented")
}
func (UnimplementedDynamicPricingServiceServer) GetFlashSaleByVariantId(context.Context, *GetFlashSaleByVariantIdRequest) (*FlashSale, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFlashSaleByVariantId not implemented")
}
func (UnimplementedDynamicPricingServiceServer) GetPromoByCode(context.Context, *GetPromoByCodeRequest) (*Promo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPromoByCode not implemented")
}
func (UnimplementedDynamicPricingServiceServer) ApplyPromo(context.Context, *ApplyPromoRequest) (*ApplyPromoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyPromo not implemented")
}
func (UnimplementedDynamicPricingServiceServer) DecrementFlashSaleStock(context.Context, *DecrementFlashSaleStockRequest) (*DecrementFlashSaleStockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DecrementFlashSaleStock not implemented")
}
func (UnimplementedDynamicPricingServiceServer) IncrementFlashSaleUsage(context.Context, *IncrementFlashSaleUsageRequest) (*IncrementFlashSaleUsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IncrementFlashSaleUsage not implemented")
}
func (UnimplementedDynamicPricingServiceServer) GetPromoUsage(context.Context, *GetPromoUsageRequest) (*PromoUsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPromoUsage not implemented")
}
func (UnimplementedDynamicPricingServiceServer) mustEmbedUnimplementedDynamicPricingServiceServer() {}
func (UnimplementedDynamicPricingServiceServer) testEmbeddedByValue()                               {}

// UnsafeDynamicPricingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DynamicPricingServiceServer will
// result in compilation errors.
type UnsafeDynamicPricingServiceServer interface {
	mustEmbedUnimplementedDynamicPricingServiceServer()
}

func RegisterDynamicPricingServiceServer(s grpc.ServiceRegistrar, srv DynamicPricingServiceServer) {
	// If the following call panics, it indicates UnimplementedDynamicPricingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DynamicPricingService_ServiceDesc, srv)
}

func _DynamicPricingService_GetFlashSaleByProductId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlashSaleByProductIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicPricingServiceServer).GetFlashSaleByProductId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamicPricingService_GetFlashSaleByProductId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicPricingServiceServer).GetFlashSaleByProductId(ctx, req.(*GetFlashSaleByProductIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicPricingService_GetFlashSaleByVariantId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlashSaleByVariantIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicPricingServiceServer).GetFlashSaleByVariantId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamicPricingService_GetFlashSaleByVariantId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicPricingServiceServer).GetFlashSaleByVariantId(ctx, req.(*GetFlashSaleByVariantIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicPricingService_GetPromoByCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPromoByCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicPricingServiceServer).GetPromoByCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamicPricingService_GetPromoByCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicPricingServiceServer).GetPromoByCode(ctx, req.(*GetPromoByCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicPricingService_ApplyPromo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyPromoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicPricingServiceServer).ApplyPromo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamicPricingService_ApplyPromo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicPricingServiceServer).ApplyPromo(ctx, req.(*ApplyPromoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicPricingService_DecrementFlashSaleStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecrementFlashSaleStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicPricingServiceServer).DecrementFlashSaleStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamicPricingService_DecrementFlashSaleStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicPricingServiceServer).DecrementFlashSaleStock(ctx, req.(*DecrementFlashSaleStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicPricingService_IncrementFlashSaleUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementFlashSaleUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicPricingServiceServer).IncrementFlashSaleUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamicPricingService_IncrementFlashSaleUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicPricingServiceServer).IncrementFlashSaleUsage(ctx, req.(*IncrementFlashSaleUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicPricingService_GetPromoUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPromoUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicPricingServiceServer).GetPromoUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamicPricingService_GetPromoUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicPricingServiceServer).GetPromoUsage(ctx, req.(*GetPromoUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DynamicPricingService_ServiceDesc is the grpc.ServiceDesc for DynamicPricingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DynamicPricingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dynamic_pricing.DynamicPricingService",
	HandlerType: (*DynamicPricingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFlashSaleByProductId",
			Handler:    _DynamicPricingService_GetFlashSaleByProductId_Handler,
		},
		{
			MethodName: "GetFlashSaleByVariantId",
			Handler:    _DynamicPricingService_GetFlashSaleByVariantId_Handler,
		},
		{
			MethodName: "GetPromoByCode",
			Handler:    _DynamicPricingService_GetPromoByCode_Handler,
		},
		{
			MethodName: "ApplyPromo",
			Handler:    _DynamicPricingService_ApplyPromo_Handler,
		},
		{
			MethodName: "DecrementFlashSaleStock",
			Handler:    _DynamicPricingService_DecrementFlashSaleStock_Handler,
		},
		{
			MethodName: "IncrementFlashSaleUsage",
			Handler:    _DynamicPricingService_IncrementFlashSaleUsage_Handler,
		},
		{
			MethodName: "GetPromoUsage",
			Handler:    _DynamicPricingService_GetPromoUsage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dynamic-pricing.proto",
}
