admin, flash-sales, create
admin, flash-sales, delete
admin, flash-sales, read
admin, flash-sales, update
admin, promos, apply
admin, promos, create
admin, promos, delete
admin, promos, read
admin, promos, update
role_1, categories, manage
role_1, flash_sales, manage
role_3, categories, manage
role_3, flash_sales, manage
role_5, categories, manage
role_5, flash_sales, manage
role_7, categories, manage
role_7, flash_sales, manage
role_9, categories, manage
role_9, flash_sales, manage
staff, flash-sales, create
staff, flash-sales, delete
staff, flash-sales, read
staff, promos, create
staff, promos, delete
staff, promos, read
tenant, promos, apply
