admin, categories, create
admin, categories, delete
admin, categories, read
admin, categories, update
admin, product-images, create
admin, product-images, delete
admin, product-images, read
admin, products, create
admin, products, delete
admin, products, read
admin, products, update
admin, variants, create
admin, variants, delete
admin, variants, read
admin, variants, update
role_1, products, write
role_1, roles, write
role_3, products, write
role_3, roles, write
role_5, products, write
role_5, roles, write
role_7, products, write
role_7, roles, write
role_9, products, write
role_9, roles, write
staff, categories, read
staff, product-images, create
staff, product-images, delete
staff, product-images, read
staff, products, create
staff, products, delete
staff, products, read
staff, products, update
staff, variants, create
staff, variants, read
staff, variants, update
