// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/product.proto

package productpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_proto_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsRequest) Reset() {
	*x = GetProductsRequest{}
	mi := &file_proto_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsRequest) ProtoMessage() {}

func (x *GetProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsRequest.ProtoReflect.Descriptor instead.
func (*GetProductsRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetProductsByCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsByCategoryRequest) Reset() {
	*x = GetProductsByCategoryRequest{}
	mi := &file_proto_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsByCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsByCategoryRequest) ProtoMessage() {}

func (x *GetProductsByCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsByCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetProductsByCategoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{2}
}

func (x *GetProductsByCategoryRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

type ProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductsResponse) Reset() {
	*x = ProductsResponse{}
	mi := &file_proto_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductsResponse) ProtoMessage() {}

func (x *ProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductsResponse.ProtoReflect.Descriptor instead.
func (*ProductsResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{3}
}

func (x *ProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type Product struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId      string                 `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName    string                 `protobuf:"bytes,3,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Name            string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Slug            string                 `protobuf:"bytes,5,opt,name=slug,proto3" json:"slug,omitempty"`
	Description     string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Price           int64                  `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	Stock           int64                  `protobuf:"varint,8,opt,name=stock,proto3" json:"stock,omitempty"`
	StockReserved   int64                  `protobuf:"varint,9,opt,name=stock_reserved,json=stockReserved,proto3" json:"stock_reserved,omitempty"`
	IsActive        bool                   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsPromoExcluded bool                   `protobuf:"varint,11,opt,name=is_promo_excluded,json=isPromoExcluded,proto3" json:"is_promo_excluded,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Variants        []*ProductVariant      `protobuf:"bytes,14,rep,name=variants,proto3" json:"variants,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_proto_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{4}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *Product) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Product) GetStockReserved() int64 {
	if x != nil {
		return x.StockReserved
	}
	return 0
}

func (x *Product) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Product) GetIsPromoExcluded() bool {
	if x != nil {
		return x.IsPromoExcluded
	}
	return false
}

func (x *Product) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Product) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Product) GetVariants() []*ProductVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

type ProductVariant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Sku           string                 `protobuf:"bytes,4,opt,name=sku,proto3" json:"sku,omitempty"`
	Price         int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int64                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	StockReserved int64                  `protobuf:"varint,7,opt,name=stock_reserved,json=stockReserved,proto3" json:"stock_reserved,omitempty"`
	IsActive      bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,9,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductVariant) Reset() {
	*x = ProductVariant{}
	mi := &file_proto_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductVariant) ProtoMessage() {}

func (x *ProductVariant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductVariant.ProtoReflect.Descriptor instead.
func (*ProductVariant) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{5}
}

func (x *ProductVariant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductVariant) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductVariant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductVariant) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ProductVariant) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductVariant) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductVariant) GetStockReserved() int64 {
	if x != nil {
		return x.StockReserved
	}
	return 0
}

func (x *ProductVariant) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ProductVariant) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type ReserveStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         []*StockItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveStockRequest) Reset() {
	*x = ReserveStockRequest{}
	mi := &file_proto_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockRequest) ProtoMessage() {}

func (x *ReserveStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockRequest.ProtoReflect.Descriptor instead.
func (*ReserveStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{6}
}

func (x *ReserveStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReserveStockRequest) GetItems() []*StockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type StockItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VariantId     string                 `protobuf:"bytes,2,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockItem) Reset() {
	*x = StockItem{}
	mi := &file_proto_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockItem) ProtoMessage() {}

func (x *StockItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockItem.ProtoReflect.Descriptor instead.
func (*StockItem) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{7}
}

func (x *StockItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StockItem) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *StockItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ReserveStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveStockResponse) Reset() {
	*x = ReserveStockResponse{}
	mi := &file_proto_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockResponse) ProtoMessage() {}

func (x *ReserveStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockResponse.ProtoReflect.Descriptor instead.
func (*ReserveStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{8}
}

func (x *ReserveStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReserveStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReleaseStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         []*StockItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseStockRequest) Reset() {
	*x = ReleaseStockRequest{}
	mi := &file_proto_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseStockRequest) ProtoMessage() {}

func (x *ReleaseStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseStockRequest.ProtoReflect.Descriptor instead.
func (*ReleaseStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{9}
}

func (x *ReleaseStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReleaseStockRequest) GetItems() []*StockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReleaseStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseStockResponse) Reset() {
	*x = ReleaseStockResponse{}
	mi := &file_proto_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseStockResponse) ProtoMessage() {}

func (x *ReleaseStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseStockResponse.ProtoReflect.Descriptor instead.
func (*ReleaseStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{10}
}

func (x *ReleaseStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReleaseStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConfirmStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         []*StockItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmStockRequest) Reset() {
	*x = ConfirmStockRequest{}
	mi := &file_proto_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmStockRequest) ProtoMessage() {}

func (x *ConfirmStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmStockRequest.ProtoReflect.Descriptor instead.
func (*ConfirmStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{11}
}

func (x *ConfirmStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ConfirmStockRequest) GetItems() []*StockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ConfirmStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmStockResponse) Reset() {
	*x = ConfirmStockResponse{}
	mi := &file_proto_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmStockResponse) ProtoMessage() {}

func (x *ConfirmStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmStockResponse.ProtoReflect.Descriptor instead.
func (*ConfirmStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{12}
}

func (x *ConfirmStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfirmStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_product_proto protoreflect.FileDescriptor

const file_proto_product_proto_rawDesc = "" +
	"\n" +
	"\x13proto/product.proto\x12\aproduct\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"&\n" +
	"\x12GetProductsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"?\n" +
	"\x1cGetProductsByCategoryRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\"@\n" +
	"\x10ProductsResponse\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.product.ProductR\bproducts\"\xb8\x03\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\tR\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\x03 \x01(\tR\fcategoryName\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x05 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\a \x01(\x03R\x05price\x12\x14\n" +
	"\x05stock\x18\b \x01(\x03R\x05stock\x12%\n" +
	"\x0estock_reserved\x18\t \x01(\x03R\rstockReserved\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\x12*\n" +
	"\x11is_promo_excluded\x18\v \x01(\bR\x0fisPromoExcluded\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\x123\n" +
	"\bvariants\x18\x0e \x03(\v2\x17.product.ProductVariantR\bvariants\"\xdd\x02\n" +
	"\x0eProductVariant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n" +
	"\x03sku\x18\x04 \x01(\tR\x03sku\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x03R\x05stock\x12%\n" +
	"\x0estock_reserved\x18\a \x01(\x03R\rstockReserved\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\x12G\n" +
	"\n" +
	"attributes\x18\t \x03(\v2'.product.ProductVariant.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Z\n" +
	"\x13ReserveStockRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12(\n" +
	"\x05items\x18\x02 \x03(\v2\x12.product.StockItemR\x05items\"e\n" +
	"\tStockItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x02 \x01(\tR\tvariantId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"J\n" +
	"\x14ReserveStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"Z\n" +
	"\x13ReleaseStockRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12(\n" +
	"\x05items\x18\x02 \x03(\v2\x12.product.StockItemR\x05items\"J\n" +
	"\x14ReleaseStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"Z\n" +
	"\x13ConfirmStockRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12(\n" +
	"\x05items\x18\x02 \x03(\v2\x12.product.StockItemR\x05items\"J\n" +
	"\x14ConfirmStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xd5\x03\n" +
	"\x0eProductService\x12:\n" +
	"\n" +
	"GetProduct\x12\x1a.product.GetProductRequest\x1a\x10.product.Product\x12E\n" +
	"\vGetProducts\x12\x1b.product.GetProductsRequest\x1a\x19.product.ProductsResponse\x12Y\n" +
	"\x15GetProductsByCategory\x12%.product.GetProductsByCategoryRequest\x1a\x19.product.ProductsResponse\x12K\n" +
	"\fReserveStock\x12\x1c.product.ReserveStockRequest\x1a\x1d.product.ReserveStockResponse\x12K\n" +
	"\fReleaseStock\x12\x1c.product.ReleaseStockRequest\x1a\x1d.product.ReleaseStockResponse\x12K\n" +
	"\fConfirmStock\x12\x1c.product.ConfirmStockRequest\x1a\x1d.product.ConfirmStockResponseB/Z-kaffein/order-service/proto/product;productpbb\x06proto3"

var (
	file_proto_product_proto_rawDescOnce sync.Once
	file_proto_product_proto_rawDescData []byte
)

func file_proto_product_proto_rawDescGZIP() []byte {
	file_proto_product_proto_rawDescOnce.Do(func() {
		file_proto_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_proto_rawDesc), len(file_proto_product_proto_rawDesc)))
	})
	return file_proto_product_proto_rawDescData
}

var file_proto_product_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_product_proto_goTypes = []any{
	(*GetProductRequest)(nil),            // 0: product.GetProductRequest
	(*GetProductsRequest)(nil),           // 1: product.GetProductsRequest
	(*GetProductsByCategoryRequest)(nil), // 2: product.GetProductsByCategoryRequest
	(*ProductsResponse)(nil),             // 3: product.ProductsResponse
	(*Product)(nil),                      // 4: product.Product
	(*ProductVariant)(nil),               // 5: product.ProductVariant
	(*ReserveStockRequest)(nil),          // 6: product.ReserveStockRequest
	(*StockItem)(nil),                    // 7: product.StockItem
	(*ReserveStockResponse)(nil),         // 8: product.ReserveStockResponse
	(*ReleaseStockRequest)(nil),          // 9: product.ReleaseStockRequest
	(*ReleaseStockResponse)(nil),         // 10: product.ReleaseStockResponse
	(*ConfirmStockRequest)(nil),          // 11: product.ConfirmStockRequest
	(*ConfirmStockResponse)(nil),         // 12: product.ConfirmStockResponse
	nil,                                  // 13: product.ProductVariant.AttributesEntry
}
var file_proto_product_proto_depIdxs = []int32{
	4,  // 0: product.ProductsResponse.products:type_name -> product.Product
	5,  // 1: product.Product.variants:type_name -> product.ProductVariant
	13, // 2: product.ProductVariant.attributes:type_name -> product.ProductVariant.AttributesEntry
	7,  // 3: product.ReserveStockRequest.items:type_name -> product.StockItem
	7,  // 4: product.ReleaseStockRequest.items:type_name -> product.StockItem
	7,  // 5: product.ConfirmStockRequest.items:type_name -> product.StockItem
	0,  // 6: product.ProductService.GetProduct:input_type -> product.GetProductRequest
	1,  // 7: product.ProductService.GetProducts:input_type -> product.GetProductsRequest
	2,  // 8: product.ProductService.GetProductsByCategory:input_type -> product.GetProductsByCategoryRequest
	6,  // 9: product.ProductService.ReserveStock:input_type -> product.ReserveStockRequest
	9,  // 10: product.ProductService.ReleaseStock:input_type -> product.ReleaseStockRequest
	11, // 11: product.ProductService.ConfirmStock:input_type -> product.ConfirmStockRequest
	4,  // 12: product.ProductService.GetProduct:output_type -> product.Product
	3,  // 13: product.ProductService.GetProducts:output_type -> product.ProductsResponse
	3,  // 14: product.ProductService.GetProductsByCategory:output_type -> product.ProductsResponse
	8,  // 15: product.ProductService.ReserveStock:output_type -> product.ReserveStockResponse
	10, // 16: product.ProductService.ReleaseStock:output_type -> product.ReleaseStockResponse
	12, // 17: product.ProductService.ConfirmStock:output_type -> product.ConfirmStockResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_product_proto_init() }
func file_proto_product_proto_init() {
	if File_proto_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_proto_rawDesc), len(file_proto_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_proto_goTypes,
		DependencyIndexes: file_proto_product_proto_depIdxs,
		MessageInfos:      file_proto_product_proto_msgTypes,
	}.Build()
	File_proto_product_proto = out.File
	file_proto_product_proto_goTypes = nil
	file_proto_product_proto_depIdxs = nil
}
